// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth

import (
	"context"
	"fmt"

	authv1 "github.com/pivaldi/mmw-contracts/gen/go/auth/v1"
)

type AuthPrivateService interface {
	ValidateToken(ctx context.Context, req *authv1.ValidateTokenRequest) (*authv1.ValidateTokenResponse, error)
}

var ErrAuthPrivateServiceUnavailable = fmt.Errorf("auth private service unavailable")

type NoopAuthPrivateService struct{}

var _ AuthPrivateService = (*NoopAuthPrivateService)(nil)

func (NoopAuthPrivateService) ValidateToken(_ context.Context, _ *authv1.ValidateTokenRequest) (*authv1.ValidateTokenResponse, error) {
	return nil, ErrAuthPrivateServiceUnavailable
}
