// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth

import (
	"context"
	"fmt"

	authv1 "github.com/pivaldi/mmw-contracts/gen/go/auth/v1"
)

type AuthService interface {
	Register(ctx context.Context, req *authv1.RegisterRequest) (*authv1.RegisterResponse, error)
	Login(ctx context.Context, req *authv1.LoginRequest) (*authv1.LoginResponse, error)
	ValidateToken(ctx context.Context, req *authv1.ValidateTokenRequest) (*authv1.ValidateTokenResponse, error)
	ChangePassword(ctx context.Context, req *authv1.ChangePasswordRequest) (*authv1.ChangePasswordResponse, error)
	DeleteUser(ctx context.Context, req *authv1.DeleteUserRequest) (*authv1.DeleteUserResponse, error)
}

var _ AuthService = (*InprocClient)(nil)

type InprocClient struct{ server AuthService }

func NewInprocClient(server AuthService) *InprocClient {
	return &InprocClient{server: server}
}

func (c *InprocClient) Register(ctx context.Context, req *authv1.RegisterRequest) (*authv1.RegisterResponse, error) {
	resp, err := c.server.Register(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) Login(ctx context.Context, req *authv1.LoginRequest) (*authv1.LoginResponse, error) {
	resp, err := c.server.Login(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) ValidateToken(ctx context.Context, req *authv1.ValidateTokenRequest) (*authv1.ValidateTokenResponse, error) {
	resp, err := c.server.ValidateToken(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) ChangePassword(ctx context.Context, req *authv1.ChangePasswordRequest) (*authv1.ChangePasswordResponse, error) {
	resp, err := c.server.ChangePassword(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) DeleteUser(ctx context.Context, req *authv1.DeleteUserRequest) (*authv1.DeleteUserResponse, error) {
	resp, err := c.server.DeleteUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

var ErrAuthServiceUnavailable = fmt.Errorf("auth service unavailable")

type NoopAuthService struct{}

var _ AuthService = (*NoopAuthService)(nil)

func (NoopAuthService) Register(_ context.Context, _ *authv1.RegisterRequest) (*authv1.RegisterResponse, error) {
	return nil, ErrAuthServiceUnavailable
}

func (NoopAuthService) Login(_ context.Context, _ *authv1.LoginRequest) (*authv1.LoginResponse, error) {
	return nil, ErrAuthServiceUnavailable
}

func (NoopAuthService) ValidateToken(_ context.Context, _ *authv1.ValidateTokenRequest) (*authv1.ValidateTokenResponse, error) {
	return nil, ErrAuthServiceUnavailable
}

func (NoopAuthService) ChangePassword(_ context.Context, _ *authv1.ChangePasswordRequest) (*authv1.ChangePasswordResponse, error) {
	return nil, ErrAuthServiceUnavailable
}

func (NoopAuthService) DeleteUser(_ context.Context, _ *authv1.DeleteUserRequest) (*authv1.DeleteUserResponse, error) {
	return nil, ErrAuthServiceUnavailable
}
