// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth

import authv1 "github.com/pivaldi/mmw-contracts/gen/go/auth/v1"

const (
	ErrorCodeInvalidLogin       = authv1.AuthErrorCode_AUTH_ERROR_CODE_INVALID_LOGIN
	ErrorCodeInvalidPassword    = authv1.AuthErrorCode_AUTH_ERROR_CODE_INVALID_PASSWORD
	ErrorCodeInvalidCredentials = authv1.AuthErrorCode_AUTH_ERROR_CODE_INVALID_CREDENTIALS
	ErrorCodeInvalidToken       = authv1.AuthErrorCode_AUTH_ERROR_CODE_INVALID_TOKEN
	ErrorCodeUserNotFound       = authv1.AuthErrorCode_AUTH_ERROR_CODE_USER_NOT_FOUND
	ErrorCodeUserAlreadyExists  = authv1.AuthErrorCode_AUTH_ERROR_CODE_USER_ALREADY_EXISTS
)
