// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth

import authv1 "github.com/pivaldi/mmw-contracts/gen/go/auth/v1"

const (
	TopicUserRegistered  = "auth.user.registered.v1"
	TopicUserDeleted     = "auth.user.deleted.v1"
	TopicPasswordChanged = "auth.user.password_changed.v1"
	TopicUserLoggedIn    = "auth.user.logged_in.v1"
)

var Topics = []string{
	TopicUserRegistered,
	TopicUserDeleted,
	TopicPasswordChanged,
	TopicUserLoggedIn,
}

type UserRegisteredEvent = authv1.UserRegisteredEvent
type UserDeletedEvent = authv1.UserDeletedEvent
type PasswordChangedEvent = authv1.PasswordChangedEvent
type UserLoggedInEvent = authv1.UserLoggedInEvent
