// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth

import (
	"context"
	"fmt"

	authv1 "github.com/pivaldi/mmw-contracts/gen/go/auth/v1"
)

// AuthService is the combined interface for in-process consumers.
type AuthService interface {
	AuthPublicService
	AuthPrivateService
}

var _ AuthPublicService = (*InprocClient)(nil)
var _ AuthPrivateService = (*InprocClient)(nil)

type InprocClient struct{ server AuthService }

func NewInprocClient(server AuthService) *InprocClient {
	return &InprocClient{server: server}
}

func (c *InprocClient) Register(ctx context.Context, req *authv1.RegisterRequest) (*authv1.RegisterResponse, error) {
	resp, err := c.server.Register(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) Login(ctx context.Context, req *authv1.LoginRequest) (*authv1.LoginResponse, error) {
	resp, err := c.server.Login(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) ChangePassword(ctx context.Context, req *authv1.ChangePasswordRequest) (*authv1.ChangePasswordResponse, error) {
	resp, err := c.server.ChangePassword(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) DeleteUser(ctx context.Context, req *authv1.DeleteUserRequest) (*authv1.DeleteUserResponse, error) {
	resp, err := c.server.DeleteUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) ValidateToken(ctx context.Context, req *authv1.ValidateTokenRequest) (*authv1.ValidateTokenResponse, error) {
	resp, err := c.server.ValidateToken(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}
