// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChangePasswordRequest, ChangePasswordResponse, DeleteUserRequest, DeleteUserResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, ValidateTokenRequest, ValidateTokenResponse } from "./auth_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AuthPublicService exposes endpoints reachable by unauthenticated clients.
 *
 * @generated from service auth.v1.AuthPublicService
 */
export const AuthPublicService = {
  typeName: "auth.v1.AuthPublicService",
  methods: {
    /**
     * Register creates a new user account.
     *
     * @generated from rpc auth.v1.AuthPublicService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Login authenticates a user and returns a session token.
     *
     * @generated from rpc auth.v1.AuthPublicService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ChangePassword updates a user's password after verifying the old one.
     *
     * @generated from rpc auth.v1.AuthPublicService.ChangePassword
     */
    changePassword: {
      name: "ChangePassword",
      I: ChangePasswordRequest,
      O: ChangePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteUser removes a user from the system.
     *
     * @generated from rpc auth.v1.AuthPublicService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: DeleteUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * AuthPrivateService exposes endpoints reachable only by internal services.
 *
 * @generated from service auth.v1.AuthPrivateService
 */
export const AuthPrivateService = {
  typeName: "auth.v1.AuthPrivateService",
  methods: {
    /**
     * ValidateToken checks if a token is valid and returns the user's identity.
     *
     * @generated from rpc auth.v1.AuthPrivateService.ValidateToken
     */
    validateToken: {
      name: "ValidateToken",
      I: ValidateTokenRequest,
      O: ValidateTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

