// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: todo/v1/todo.proto

package todo

import todov1 "github.com/pivaldi/mmw-contracts/gen/go/todo/v1"

const (
	TopicUserTasksDeleted  = "todo.userTasks.deleted.v1"
	TopicUserTaskCreated   = "todo.userTasks.created.v1"
	TopicUserTaskUpdated   = "todo.userTasks.updated.v1"
	TopicUserTaskReopened  = "todo.userTasks.reopened.v1"
	TopicUserTaskCompleted = "todo.userTasks.completed.v1"
	TopicUserTaskDeleted   = "todo.userTask.deleted.v1"
)

var AllEvents = []string{
	TopicUserTasksDeleted,
	TopicUserTaskCreated,
	TopicUserTaskUpdated,
	TopicUserTaskReopened,
	TopicUserTaskCompleted,
	TopicUserTaskDeleted,
}

type UserTasksDeletedEvent = todov1.UserTasksDeletedEvent
type UserTaskCreatedEvent = todov1.UserTaskCreatedEvent
type UserTaskUpdatedEvent = todov1.UserTaskUpdatedEvent
type UserTaskReopenedEvent = todov1.UserTaskReopenedEvent
type UserTaskCompletedEvent = todov1.UserTaskCompletedEvent
type UserTaskDeletedEvent = todov1.UserTaskDeletedEvent
