// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: todo/v1/todo.proto

package todo

import (
	"context"
	"fmt"

	todov1 "github.com/pivaldi/mmw-contracts/gen/go/todo/v1"
)

var _ TodoService = (*InprocClient)(nil)

type InprocClient struct{ server TodoService }

func NewInprocClient(server TodoService) *InprocClient {
	return &InprocClient{server: server}
}

func (c *InprocClient) CreateTodo(ctx context.Context, req *todov1.CreateTodoRequest) (*todov1.CreateTodoResponse, error) {
	resp, err := c.server.CreateTodo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) GetTodo(ctx context.Context, req *todov1.GetTodoRequest) (*todov1.GetTodoResponse, error) {
	resp, err := c.server.GetTodo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) UpdateTodo(ctx context.Context, req *todov1.UpdateTodoRequest) (*todov1.UpdateTodoResponse, error) {
	resp, err := c.server.UpdateTodo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) CompleteTodo(ctx context.Context, req *todov1.CompleteTodoRequest) (*todov1.CompleteTodoResponse, error) {
	resp, err := c.server.CompleteTodo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) ReopenTodo(ctx context.Context, req *todov1.ReopenTodoRequest) (*todov1.ReopenTodoResponse, error) {
	resp, err := c.server.ReopenTodo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) DeleteTodo(ctx context.Context, req *todov1.DeleteTodoRequest) (*todov1.DeleteTodoResponse, error) {
	resp, err := c.server.DeleteTodo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}

func (c *InprocClient) ListTodos(ctx context.Context, req *todov1.ListTodosRequest) (*todov1.ListTodosResponse, error) {
	resp, err := c.server.ListTodos(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("%w", err)
	}
	return resp, nil
}
