// protoc-gen-go-contracts is a buf/protoc plugin that generates the boilerplate
// definitions layer from proto service definitions:
//
//	definitions/{domain}/contract.go  — interface, InprocClient, NoopService
//	definitions/{domain}/errors.go    — const aliases for *ErrorCode enum values
//	definitions/{domain}/events.go    — TopicXxx constants, AllEvents slice, type aliases
//	                                    (requires (options.v1.topic) on each *Event message)
//
// Build and install:
//
//	go build -o $(go env GOPATH)/bin/protoc-gen-go-contracts ./cmd/protoc-gen-go-contracts
//
// Then add to buf.gen.yaml:
//
//	plugins:
//	  - local: protoc-gen-go-contracts
//	    out: .
package main

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/types/pluginpb"
)

// topicExtensionNumber is the field number of (options.v1.topic) defined in
// contracts/proto/options/v1/options.proto.
const topicExtensionNumber = 50000

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			processFile(gen, f)
		}

		return nil
	})
}

func processFile(gen *protogen.Plugin, f *protogen.File) {
	pkg := domainPkg(f)           // e.g. "todo"
	alias := goAlias(f)           // e.g. "todov1"
	imp := string(f.GoImportPath) // e.g. "github.com/pivaldi/mmw-contracts/gen/go/todo/v1"

	if len(f.Services) > 0 {
		genContract(gen, f, pkg, alias, imp)
	}
	if e := errorCodeEnum(f); e != nil {
		genErrors(gen, f, pkg, alias, imp, e)
	}
	if msgs := eventMessages(f); len(msgs) > 0 {
		genEvents(gen, f, pkg, alias, imp, msgs)
	}
}

// ── contract.go ───────────────────────────────────────────────────────────────

func genContract(gen *protogen.Plugin, f *protogen.File, pkg, alias, imp string) {
	svc := f.Services[0]
	svcName := svc.GoName
	noopName := "Noop" + svcName
	errVar := "Err" + svcName + "Unavailable"

	g := gen.NewGeneratedFile("definitions/"+pkg+"/contract_gen.go", "")
	w := printer(g)

	writeContractHeader(w, f.Desc.Path(), pkg, alias, imp)
	writeInterface(w, svcName, alias, svc.Methods)
	writeInprocClient(w, svcName, alias, svc.Methods)
	writeNoopService(w, svcName, noopName, errVar, alias, svc.Methods)
}

func writeContractHeader(w func(string, ...any), source, pkg, alias, imp string) {
	w("// Code generated by protoc-gen-go-contracts. DO NOT EDIT.")
	w("// source: %s", source)
	w("")
	w("package %s", pkg)
	w("")
	w("import (")
	w(`	"context"`)
	w(`	"fmt"`)
	w("")
	w("	%s %q", alias, imp)
	w(")")
	w("")
}

func writeInterface(w func(string, ...any), svcName, alias string, methods []*protogen.Method) {
	w("type %s interface {", svcName)
	for _, m := range methods {
		w("	%s(ctx context.Context, req *%s.%s) (*%s.%s, error)",
			m.GoName, alias, m.Input.GoIdent.GoName, alias, m.Output.GoIdent.GoName)
	}
	w("}")
	w("")
}

func writeInprocClient(w func(string, ...any), svcName, alias string, methods []*protogen.Method) {
	w("var _ %s = (*InprocClient)(nil)", svcName)
	w("")
	w("type InprocClient struct{ server %s }", svcName)
	w("")
	w("func NewInprocClient(server %s) *InprocClient {", svcName)
	w("	return &InprocClient{server: server}")
	w("}")
	w("")
	for _, m := range methods {
		inT := alias + "." + m.Input.GoIdent.GoName
		outT := alias + "." + m.Output.GoIdent.GoName
		w("func (c *InprocClient) %s(ctx context.Context, req *%s) (*%s, error) {", m.GoName, inT, outT)
		w("	resp, err := c.server.%s(ctx, req)", m.GoName)
		w("	if err != nil {")
		w(`		return nil, fmt.Errorf("%w", err)`)
		w("	}")
		w("	return resp, nil")
		w("}")
		w("")
	}
}

func writeNoopService(w func(string, ...any), svcName, noopName, errVar, alias string, methods []*protogen.Method) {
	w("var %s = fmt.Errorf(%q)", errVar, lowerWords(svcName)+" unavailable")
	w("")
	w("type %s struct{}", noopName)
	w("")
	w("var _ %s = (*%s)(nil)", svcName, noopName)
	w("")
	for _, m := range methods {
		inT := alias + "." + m.Input.GoIdent.GoName
		outT := alias + "." + m.Output.GoIdent.GoName
		w("func (%s) %s(_ context.Context, _ *%s) (*%s, error) {", noopName, m.GoName, inT, outT)
		w("	return nil, %s", errVar)
		w("}")
		w("")
	}
}

// ── errors.go ─────────────────────────────────────────────────────────────────

func genErrors(gen *protogen.Plugin, f *protogen.File, pkg, alias, imp string, enum *protogen.Enum) {
	g := gen.NewGeneratedFile("definitions/"+pkg+"/errors_gen.go", "")
	w := printer(g)

	w("// Code generated by protoc-gen-go-contracts. DO NOT EDIT.")
	w("// source: %s", f.Desc.Path())
	w("")
	w("package %s", pkg)
	w("")
	w("import %s %q", alias, imp)
	w("")
	w("const (")

	prefix := enumValuePrefix(string(enum.Desc.Name())) // e.g. "AUTH_ERROR_CODE_"
	for _, v := range enum.Values {
		if v.Desc.Number() == 0 {
			continue // skip UNSPECIFIED
		}
		rawName := string(v.Desc.Name())                                // AUTH_ERROR_CODE_INVALID_LOGIN
		shortName := snakeToPascal(strings.TrimPrefix(rawName, prefix)) // InvalidLogin
		w("	ErrorCode%s = %s.%s_%s", shortName, alias, enum.GoIdent.GoName, rawName)
	}
	w(")")
}

// ── events.go ─────────────────────────────────────────────────────────────────

type topicEntry struct {
	constName string // e.g. "TopicUserDeleted"
	topic     string // e.g. "auth.user.deleted.v1"
}

func genEvents(gen *protogen.Plugin, f *protogen.File, pkg, alias, imp string, msgs []*protogen.Message) {
	// Collect topic entries from messages that carry (options.v1.topic).
	var topics []topicEntry
	for _, m := range msgs {
		if t := messageTopicOption(m); t != "" {
			constName := "Topic" + strings.TrimSuffix(m.GoIdent.GoName, "Event")
			topics = append(topics, topicEntry{constName, t})
		}
	}

	g := gen.NewGeneratedFile("definitions/"+pkg+"/events_gen.go", "")
	w := printer(g)

	w("// Code generated by protoc-gen-go-contracts. DO NOT EDIT.")
	w("// source: %s", f.Desc.Path())
	w("")
	w("package %s", pkg)
	w("")
	w("import %s %q", alias, imp)
	w("")

	if len(topics) > 0 {
		w("const (")
		for _, t := range topics {
			w("	%s = %q", t.constName, t.topic)
		}
		w(")")
		w("")
		w("var AllEvents = []string{")
		for _, t := range topics {
			w("	%s,", t.constName)
		}
		w("}")
		w("")
	}

	for _, m := range msgs {
		w("type %s = %s.%s", m.GoIdent.GoName, alias, m.GoIdent.GoName)
	}
}

// ── proto helpers ─────────────────────────────────────────────────────────────

// errorCodeEnum finds the first enum whose name ends with "ErrorCode".
func errorCodeEnum(f *protogen.File) *protogen.Enum {
	for _, e := range f.Enums {
		if strings.HasSuffix(string(e.Desc.Name()), "ErrorCode") {
			return e
		}
	}

	return nil
}

// eventMessages finds messages whose name ends with "Event".
func eventMessages(f *protogen.File) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range f.Messages {
		if strings.HasSuffix(string(m.Desc.Name()), "Event") {
			out = append(out, m)
		}
	}

	return out
}

// messageTopicOption reads the (options.v1.topic) string from a message's options.
// Unregistered extensions land in the unknown fields of the options message, so we
// parse the raw bytes directly using protowire instead of importing generated code.
// Returns "" if the option is absent.
func messageTopicOption(msg *protogen.Message) string {
	opts := msg.Desc.Options()
	if opts == nil {
		return ""
	}
	raw := opts.ProtoReflect().GetUnknown()
	for len(raw) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(raw)
		if tagLen < 0 {
			return ""
		}
		raw = raw[tagLen:]
		if num == topicExtensionNumber && typ == protowire.BytesType {
			v, n := protowire.ConsumeBytes(raw)
			if n < 0 {
				return ""
			}

			return string(v)
		}
		// Skip this field's value to advance past it.
		var valLen int
		switch typ {
		case protowire.VarintType:
			_, valLen = protowire.ConsumeVarint(raw)
		case protowire.Fixed32Type:
			_, valLen = protowire.ConsumeFixed32(raw)
		case protowire.Fixed64Type:
			_, valLen = protowire.ConsumeFixed64(raw)
		case protowire.BytesType:
			_, valLen = protowire.ConsumeBytes(raw)
		default:
			return "" // unexpected wire type, bail out
		}
		if valLen < 0 {
			return ""
		}
		raw = raw[valLen:]
	}

	return ""
}

// ── string helpers ────────────────────────────────────────────────────────────

// domainPkg returns the non-version segment of the proto package.
// "todo.v1" → "todo", "auth.v1" → "auth"
func domainPkg(f *protogen.File) string {
	for p := range strings.SplitSeq(string(f.Desc.Package()), ".") {
		if p != "" && (p[0] != 'v' || !isDigits(p[1:])) {
			return p
		}
	}

	return string(f.Desc.Package())
}

// goAlias returns the Go import alias for the proto-generated package.
// "todo.v1" → "todov1"
func goAlias(f *protogen.File) string {
	return strings.ReplaceAll(string(f.Desc.Package()), ".", "")
}

// enumValuePrefix converts a PascalCase enum name to its SCREAMING_SNAKE prefix.
// "AuthErrorCode" → "AUTH_ERROR_CODE_"
func enumValuePrefix(name string) string {
	var b strings.Builder
	for i, r := range name {
		if unicode.IsUpper(r) && i > 0 {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToUpper(r))
	}
	b.WriteByte('_')

	return b.String()
}

// goAcronyms maps lowercase words that must be uppercased in Go identifiers.
var goAcronyms = map[string]string{
	"id":   "ID",
	"url":  "URL",
	"uri":  "URI",
	"api":  "API",
	"sql":  "SQL",
	"db":   "DB",
	"io":   "IO",
	"http": "HTTP",
}

// snakeToPascal converts SCREAMING_SNAKE to PascalCase, respecting Go acronyms.
// "INVALID_LOGIN" → "InvalidLogin", "INVALID_ID" → "InvalidID"
func snakeToPascal(s string) string {
	var b strings.Builder
	for word := range strings.SplitSeq(strings.ToLower(s), "_") {
		if word != "" {
			if acronym, ok := goAcronyms[word]; ok {
				b.WriteString(acronym)
			} else {
				b.WriteString(strings.ToUpper(word[:1]))
				b.WriteString(word[1:])
			}
		}
	}

	return b.String()
}

// lowerWords converts PascalCase to space-separated lowercase words.
// "TodoService" → "todo service"
func lowerWords(s string) string {
	var words []string
	var cur strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			words = append(words, strings.ToLower(cur.String()))
			cur.Reset()
		}
		cur.WriteRune(r)
	}
	if cur.Len() > 0 {
		words = append(words, strings.ToLower(cur.String()))
	}

	return strings.Join(words, " ")
}

// isDigits reports whether s contains only ASCII digits.
func isDigits(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}

	return s != ""
}

// printer returns a helper that writes a formatted line to g.
func printer(g *protogen.GeneratedFile) func(string, ...any) {
	return func(format string, a ...any) {
		if len(a) == 0 {
			fmt.Fprintln(g, format)
		} else {
			fmt.Fprintf(g, format+"\n", a...)
		}
	}
}
