// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: options/v1/options.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_options_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "options.v1.topic",
		Tag:           "bytes,50000,opt,name=topic",
		Filename:      "options/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// topic specifies the message-bus routing key for an event message.
	// The plugin uses this to generate TopicXxx constants and AllEvents in events.go.
	//
	// Example:
	//
	//	message UserDeletedEvent {
	//	  option (options.v1.topic) = "auth.user.deleted.v1";
	//	  ...
	//	}
	//
	// optional string topic = 50000;
	E_Topic = &file_options_v1_options_proto_extTypes[0]
)

var File_options_v1_options_proto protoreflect.FileDescriptor

const file_options_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x18options/v1/options.proto\x12\n" +
	"options.v1\x1a google/protobuf/descriptor.proto:7\n" +
	"\x05topic\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\tR\x05topicB\xa9\x01\n" +
	"\x0ecom.options.v1B\fOptionsProtoP\x01Z@github.com/pivaldi/mmw-contracts/go/network/options/v1;optionsv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Options.V1\xca\x02\n" +
	"Options\\V1\xe2\x02\x16Options\\V1\\GPBMetadata\xea\x02\vOptions::V1b\x06proto3"

var file_options_v1_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
}
var file_options_v1_options_proto_depIdxs = []int32{
	0, // 0: options.v1.topic:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_v1_options_proto_init() }
func file_options_v1_options_proto_init() {
	if File_options_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_v1_options_proto_rawDesc), len(file_options_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_options_v1_options_proto_goTypes,
		DependencyIndexes: file_options_v1_options_proto_depIdxs,
		ExtensionInfos:    file_options_v1_options_proto_extTypes,
	}.Build()
	File_options_v1_options_proto = out.File
	file_options_v1_options_proto_goTypes = nil
	file_options_v1_options_proto_depIdxs = nil
}
