// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth

import (
	"context"
	"fmt"

	authv1 "github.com/pivaldi/mmw-contracts/go/network/auth/v1"
)

type AuthPublicService interface {
	Register(ctx context.Context, req *authv1.RegisterRequest) (*authv1.RegisterResponse, error)
	Login(ctx context.Context, req *authv1.LoginRequest) (*authv1.LoginResponse, error)
	ChangePassword(ctx context.Context, req *authv1.ChangePasswordRequest) (*authv1.ChangePasswordResponse, error)
	DeleteUser(ctx context.Context, req *authv1.DeleteUserRequest) (*authv1.DeleteUserResponse, error)
}

var ErrAuthPublicServiceUnavailable = fmt.Errorf("auth public service unavailable")

type NoopAuthPublicService struct{}

var _ AuthPublicService = (*NoopAuthPublicService)(nil)

func (NoopAuthPublicService) Register(_ context.Context, _ *authv1.RegisterRequest) (*authv1.RegisterResponse, error) {
	return nil, ErrAuthPublicServiceUnavailable
}

func (NoopAuthPublicService) Login(_ context.Context, _ *authv1.LoginRequest) (*authv1.LoginResponse, error) {
	return nil, ErrAuthPublicServiceUnavailable
}

func (NoopAuthPublicService) ChangePassword(_ context.Context, _ *authv1.ChangePasswordRequest) (*authv1.ChangePasswordResponse, error) {
	return nil, ErrAuthPublicServiceUnavailable
}

func (NoopAuthPublicService) DeleteUser(_ context.Context, _ *authv1.DeleteUserRequest) (*authv1.DeleteUserResponse, error) {
	return nil, ErrAuthPublicServiceUnavailable
}
