// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file options/v1/options.proto (package options.v1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file options/v1/options.proto.
 */
export const file_options_v1_options: GenFile = /*@__PURE__*/
  fileDesc("ChhvcHRpb25zL3YxL29wdGlvbnMucHJvdG8SCm9wdGlvbnMudjE6NwoFdG9waWMSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY0IYDIAEoCVIFdG9waWNCqQEKDmNvbS5vcHRpb25zLnYxQgxPcHRpb25zUHJvdG9QAVpAZ2l0aHViLmNvbS9waXZhbGRpL21tdy1jb250cmFjdHMvZ28vbmV0d29yay9vcHRpb25zL3YxO29wdGlvbnN2MaICA09YWKoCCk9wdGlvbnMuVjHKAgpPcHRpb25zXFYx4gIWT3B0aW9uc1xWMVxHUEJNZXRhZGF0YeoCC09wdGlvbnM6OlYxYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * topic specifies the message-bus routing key for an event message.
 * The plugin uses this to generate TopicXxx constants and AllEvents in events.go.
 *
 * Example:
 *   message UserDeletedEvent {
 *     option (options.v1.topic) = "auth.user.deleted.v1";
 *     ...
 *   }
 *
 * @generated from extension: string topic = 50000;
 */
export const topic: GenExtension<MessageOptions, string> = /*@__PURE__*/
  extDesc(file_options_v1_options, 0);

