// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file common/v1/errors.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/errors.proto.
 */
export const file_common_v1_errors: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvZXJyb3JzLnByb3RvEgljb21tb24udjEiLAoLRG9tYWluRXJyb3ISDAoEY29kZRgBIAEoBRIPCgdtZXNzYWdlGAIgASgJQqEBCg1jb20uY29tbW9uLnYxQgtFcnJvcnNQcm90b1ABWj5naXRodWIuY29tL3BpdmFsZGkvbW13LWNvbnRyYWN0cy9nby9uZXR3b3JrL2NvbW1vbi92MTtjb21tb252MaICA0NYWKoCCUNvbW1vbi5WMcoCCUNvbW1vblxWMeICFUNvbW1vblxWMVxHUEJNZXRhZGF0YeoCCkNvbW1vbjo6VjFiBnByb3RvMw");

/**
 * DomainError is attached as a Connect error detail.
 * TypeScript clients call err.findDetails(DomainError) to retrieve it.
 *
 * @generated from message common.v1.DomainError
 */
export type DomainError = Message<"common.v1.DomainError"> & {
  /**
   * maps to the module-specific error enum (e.g. TodoErrorCode)
   *
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message common.v1.DomainError.
 * Use `create(DomainErrorSchema)` to create a new message.
 */
export const DomainErrorSchema: GenMessage<DomainError> = /*@__PURE__*/
  messageDesc(file_common_v1_errors, 0);

