// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: todo/v1/todo.proto

package todo

import todov1 "github.com/pivaldi/mmw-contracts/go/network/todo/v1"

const (
	ErrorCodeInvalidTitle            = todov1.TodoErrorCode_TODO_ERROR_CODE_INVALID_TITLE
	ErrorCodeInvalidDueDate          = todov1.TodoErrorCode_TODO_ERROR_CODE_INVALID_DUE_DATE
	ErrorCodeInvalidID               = todov1.TodoErrorCode_TODO_ERROR_CODE_INVALID_ID
	ErrorCodeNotFound                = todov1.TodoErrorCode_TODO_ERROR_CODE_NOT_FOUND
	ErrorCodeAlreadyExists           = todov1.TodoErrorCode_TODO_ERROR_CODE_ALREADY_EXISTS
	ErrorCodeCannotCompleteCancelled = todov1.TodoErrorCode_TODO_ERROR_CODE_CANNOT_COMPLETE_CANCELLED
	ErrorCodeCannotModifyCompleted   = todov1.TodoErrorCode_TODO_ERROR_CODE_CANNOT_MODIFY_COMPLETED
	ErrorCodeInvalidStatusTransition = todov1.TodoErrorCode_TODO_ERROR_CODE_INVALID_STATUS_TRANSITION
)
