// Code generated by protoc-gen-go-contracts. DO NOT EDIT.
// source: todo/v1/todo.proto

package todo

import (
	"context"
	"fmt"

	todov1 "github.com/pivaldi/mmw-contracts/go/network/todo/v1"
)

type TodoService interface {
	CreateTodo(ctx context.Context, req *todov1.CreateTodoRequest) (*todov1.CreateTodoResponse, error)
	GetTodo(ctx context.Context, req *todov1.GetTodoRequest) (*todov1.GetTodoResponse, error)
	UpdateTodo(ctx context.Context, req *todov1.UpdateTodoRequest) (*todov1.UpdateTodoResponse, error)
	CompleteTodo(ctx context.Context, req *todov1.CompleteTodoRequest) (*todov1.CompleteTodoResponse, error)
	ReopenTodo(ctx context.Context, req *todov1.ReopenTodoRequest) (*todov1.ReopenTodoResponse, error)
	DeleteTodo(ctx context.Context, req *todov1.DeleteTodoRequest) (*todov1.DeleteTodoResponse, error)
	ListTodos(ctx context.Context, req *todov1.ListTodosRequest) (*todov1.ListTodosResponse, error)
}

var ErrTodoServiceUnavailable = fmt.Errorf("todo service unavailable")

type NoopTodoService struct{}

var _ TodoService = (*NoopTodoService)(nil)

func (NoopTodoService) CreateTodo(_ context.Context, _ *todov1.CreateTodoRequest) (*todov1.CreateTodoResponse, error) {
	return nil, ErrTodoServiceUnavailable
}

func (NoopTodoService) GetTodo(_ context.Context, _ *todov1.GetTodoRequest) (*todov1.GetTodoResponse, error) {
	return nil, ErrTodoServiceUnavailable
}

func (NoopTodoService) UpdateTodo(_ context.Context, _ *todov1.UpdateTodoRequest) (*todov1.UpdateTodoResponse, error) {
	return nil, ErrTodoServiceUnavailable
}

func (NoopTodoService) CompleteTodo(_ context.Context, _ *todov1.CompleteTodoRequest) (*todov1.CompleteTodoResponse, error) {
	return nil, ErrTodoServiceUnavailable
}

func (NoopTodoService) ReopenTodo(_ context.Context, _ *todov1.ReopenTodoRequest) (*todov1.ReopenTodoResponse, error) {
	return nil, ErrTodoServiceUnavailable
}

func (NoopTodoService) DeleteTodo(_ context.Context, _ *todov1.DeleteTodoRequest) (*todov1.DeleteTodoResponse, error) {
	return nil, ErrTodoServiceUnavailable
}

func (NoopTodoService) ListTodos(_ context.Context, _ *todov1.ListTodosRequest) (*todov1.ListTodosResponse, error) {
	return nil, ErrTodoServiceUnavailable
}
